spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${VPS_HOST:localhost}:3306/sgms?characterEncoding=utf-8&useSSL=false
    username: oreki
    password: ${PASSWORD:root}
    hikari:
      connection-timeout: 60000
      max-lifetime: 60000
#logging:
#  level:
#    root: off